# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
