# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_scoresheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
