# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161117_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoresheet',
            unique_together=set([('subject', 'student')]),
        ),
    ]
