# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161117_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
