# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161118_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='average',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
